### ISSUE TITLE
Build fail index.js missing

### ISSUE THREAD

**Issue by FndNur1Labs** [phusion/node-sha3#101]
Got error after running init.sj. nodejs 14.x
Error: Cannot find module '/home/ecustomer/up/node_modules/sha3/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:308:19)   
    at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ecustomer/up/node_modules/cryptocurrency-stratum-pool/lib/jobManager.js:3:12)    at Module._compile (internal/modules/cjs/loader.js:1068:30)       
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/ecustomer/up/node_modules/sha3/package.json',
  requestPath: 'sha3'
}

**Comment by le2Ks** [comment]
> Got error after running init.sj. nodejs 14.x Error: Cannot find module '/home/ecustomer/up/node_modules/sha3/index.js'. Please verify that the package.json has a valid "main" entry at tryPackage (internal/modules/cjs/loader.js:308:19) at Function.Module._findPath (internal/modules/cjs/loader.js:521:18) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27) at Function.Module._load (internal/modules/cjs/loader.js:730:27) at Module.require (internal/modules/cjs/loader.js:957:19) at require (internal/modules/cjs/helpers.js:88:18) at Object. (/home/ecustomer/up/node_modules/cryptocurrency-stratum-pool/lib/jobManager.js:3:12) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) { code: 'MODULE_NOT_FOUND', path: '/home/ecustomer/up/node_modules/sha3/package.json', requestPath: 'sha3' }

Did you find a fix?
