### ISSUE TITLE
 undefined symbol: _ZN2v811HandleScopeC1Ev", source: module.js

### ISSUE THREAD

**Issue by iurimatias** [phusion/node-sha3#13]
attempting to use the sha3 package with node-webkit (now nws), throws the error above? is there any way around it?

**Comment by parkr** [comment]
Can you please provide the full error log? What version of v8 are you using?

**Comment by iurimatias** [comment]
A repo replicating the issue here https://github.com/iurimatias/nw-test

> npm install
> nw
==> runs, but the require('sha3') results in the error reported.

node version: v0.10.35

```
cyprus@cyprus-VirtualBox:~/nw-test$ npm install
npm WARN package.json new-test@ No description
npm WARN package.json new-test@ No repository field.
npm WARN package.json new-test@ No README data
\
> sha3@1.1.0 install /home/cyprus/nw-test/node_modules/sha3
> node-gyp rebuild

make: Entering directory `/home/cyprus/nw-test/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/obj.target/sha3.node
  SOLINK_MODULE(target) Release/obj.target/sha3.node: Finished
  COPY Release/sha3.node
make: Leaving directory `/home/cyprus/nw-test/node_modules/sha3/build'
sha3@1.1.0 node_modules/sha3
└── nan@1.6.1
```

```
cyprus@cyprus-VirtualBox:~/nw-test$ nw
[12091:0130/090836:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
pci id for fd 12: 80ee:beef, driver (null)
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[12091:0130/090837:ERROR:nw_shell.cc(324)] Error: /home/cyprus/nw-test/node_modules/sha3/build/Release/sha3.node: undefined symbol: _ZN2v811HandleScopeC1Ev
    at Error (native)
    at Module.load (module.js:367:32)
    at Function.Module._load (module.js:322:12)
    at Module.require (module.js:377:17)
    at require (module.js:396:17)
    at window.require (<anonymous>:4:17)
    at file:///home/cyprus/nw-test/html/index.html:4:18
[12091:0130/090837:INFO:CONSOLE(367)] "Uncaught Error: /home/cyprus/nw-test/node_modules/sha3/build/Release/sha3.node: undefined symbol: _ZN2v811HandleScopeC1Ev", source: module.js (367)
```

**Comment by parkr** [comment]
We use `nan` to maintain compatibility with Node v0.10 and Node v0.12 (which have breaking changes in the v8 versions they bundle). NW may not be compatible with `nan`.

**Comment by parkr** [comment]
Just released a new version – check that one out. Should be all fixed now.
