### ISSUE TITLE
Install error on Win7 x64 and node 0.8.18

### ISSUE THREAD

**Issue by n074v41l4bl34u** [phusion/node-sha3#2]
While installing node-sha3 1.0.0 I get following error:

```text
npm http GET https://registry.npmjs.org/sha3
npm http 304 https://registry.npmjs.org/sha3

> sha3@1.0.0 install C:\MyProject\node_modules\sha3
> node-gyp rebuild


C:\MyProject\node_modules\sha3>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\.
.\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp http GET http://nodejs.org/dist/v0.8.18/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.8.18/node.lib
gyp http 200 http://nodejs.org/dist/v0.8.18/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.8.18/node.lib
  displayIntermediateValues.cpp
  KeccakSponge.cpp
  KeccakNISTInterface.cpp
  KeccakF-1600-reference.cpp
  addon.cpp
C:\Users\KubuS\.node-gyp\0.8.18\deps\v8\include\v8.h(217): warning C4506: no definition for inline function 'v8::Persis
tent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\MyProject\node_modules\sha3\build\sha3.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\MyProject\node_modules\sha3\build\Release\sha3.lib and object C:\MyProject\node_modules\sha3\build\Release\sha3.exp
addon.obj : error LNK2001: unresolved external symbol "enum node::encoding __cdecl node::ParseEncoding(class v8::Handle
<class v8::Value>,enum node::encoding)" (?ParseEncoding@node@@YA?AW4encoding@1@V?$Handle@VValue@v8@@@v8@@W421@@Z) [C:\MyProject\node_modules\sha3\build\sha3.vcxproj]
C:\MyProject\node_modules\sha3\build\Release\sha3.node : fatal error LNK1120: 1 unresolved external
s [C:\MyProject\node_modules\sha3\build\sha3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
55:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\MyProject\node_modules\sha3
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
npm ERR! sha3@1.0.0 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the sha3@1.0.0 install script.
npm ERR! This is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install"
npm ERR! cwd C:\MyProject
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\MyProject\npm-debug.log
npm ERR! not ok code 0
```

The most important line seems to be: `addon.obj : error LNK2001: unresolved external symbol "enum node::encoding __cdecl node::ParseEncoding(class v8::Handle<class v8::Value>,enum node::encoding)" (?ParseEncoding@node@@YA?AW4encoding@1@V?$Handle@VValue@v8@@@v8@@W421@@Z) `

**Comment by parkr** [comment]
Try the latest version and let me know if it's still broken.
